#ifndef BIT_MATH_H
#define BIT_MATH_H

#define SET_BIT(REGISTER, BIT) (REGISTER |=  (1<<BIT))
#define CLR_BIT(REGISTER, BIT) (REGISTER &= ~(1<<BIT))
#define TOG_BIT(REGISTER, BIT) (REGISTER ^=  (1<<BIT))

#define SET_BIT_ATOMIC(REGISTER) (REGISTER =  1)
#define CLR_BIT_ATOMIC(REGISTER) (REGISTER =  0)
#define TOG_BIT_ATOMIC(REGISTER) (REGISTER ^= 1)

#endif